AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table for ogata user management'

Resources:
  OgataUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ogata-excel
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 50
        WriteCapacityUnits: 50